### ISSUE TITLE
Theme doesn't apply on Stylus files...

### ISSUE THREAD

**Issue by asleepinglion** [JTruax/brackets-theme-raven#1]
The theme doesn't apply on stylus files for some reason. Didn't have a chance to dig into why yet -- haven't done any development on brackets yet -- but if I have some time later this week I will see if I can submit a pull request. Figured I'd post the issue at least. :)

**Comment by JTruax** [comment]
Hey asleepinglion, thanks for letting me know.  I know Brackets only recently added support for stylus, so I will look into it.  Will keep you posted!

**Comment by JTruax** [comment]
Hey asleepinglion,

Update 1.07 now supports stylus and other preprocessor extensions.
