### ISSUE TITLE
Minimap plugin does not pick up colours

### ISSUE THREAD

**Issue by lavandongen** [JTruax/brackets-theme-raven#2]
The plugin minimap (and other plugins that add the same functionality) do not display the colours of this theme in the scrollbar.
So far this is the only theme I know to do this. And unfortunately my favourite theme as well

I have no clue why though, just wanted to mention it.

**Comment by JTruax** [comment]
Hey lavandongen,

Update 1.07 now supports the minimap plugin. Also, better support for third-party extensions.

**Comment by lavandongen** [comment]
That's great! Back to using my favourite theme! Thanks so much :)
